### PR TITLE
Allow for-of loops

### PR DESCRIPTION
**Pull request by ChrisAntaki**
- Allow for-of loops in production code (was already allowed in tests)
- Update gaa.js to use for-of loops

### CODE REVIEW

**Comment by ChrisAntaki** [comment]
I'm just going to verify this works for IE 11

**Comment by ChrisAntaki** [comment]
Ah, so AMP started allowing `for-of` on May 6th, after deciding to drop support for IE 11
https://github.com/ampproject/amphtml/pull/34249

**Comment by ChrisAntaki** [comment]
Once we drop support for IE 11 (#1834) we're good to move forward on this, I'd say

**Comment by mmmicedcoffee** [comment]
That's great news!

**Comment by samouri** [comment]
Drive-by noting that you can likely also support spread, rest, and array destructuring now without a size hit. They all depended on the iterator polyfill.

**Comment by ChrisAntaki** [comment]
Looking forward to using those modern JS features 👍

**Comment by jpettitt** [comment]
Nudge - are we able to do this now?

**Comment by ChrisAntaki** [comment]
@jpettitt Yep!

**Review by jpettitt — APPROVED** [review]

**Pull request merged**
