### PR TITLE
Updates Showcase translations

### PR DESCRIPTION
**Pull request by xiexr151e**
This updates "Already have an account?" to "Already registered? Sign in"

For context, please see b/183593738. Note that translations are actually not in place yet.

### CODE REVIEW

**Review by adolgachev — CHANGES_REQUESTED** [review]
Pending reply to John's comment. I was assuming wording changed and then another process to get them translated?

**Comment by jpettitt** [comment]
Don't merge this - we need to put in the actual translations for every language.  You can do a PR for the english version and then once you have the translations for the other languages add those in a separate PR if you want.

**Comment by xiexr151e** [comment]
Okay, I'll keep this PR as-is right now.

**Comment by adolgachev** [comment]
That process is centered more on adding strings and languages. This is an existing string being modified which would turn English in our next release.

**Pull request closed without merging**
