### PR TITLE
Make background unclickable for client side interventions

### PR DESCRIPTION
**Pull request by mhkawano**
Tested locally

b/328637765

### CODE REVIEW

**Comment by justinchou-google** [comment]
Matt just worked on something to make the background clickable so as to suppress clickthroughs to the page (not sure what the scope of that work was). https://github.com/subscriptions-project/swg-js/pull/3463

Can you check with him how these two features are supposed to coexist? Perhaps this is a conversation for Seth and Sagiv.

**Comment by mhkawano** [comment]
These are client side prompt changes to keep the behavior consistent with @mborof 's work.

**Comment by mborof** [comment]
It looks correct to me.  But to validate, ensure it does these two things when the background is clickable/closable:
  1) You can reopen the popup (if the UI allows it).  This was a problem with the original method of closing (re-opening failed)
  2) It logs that the user clicked the close button.

**Review by justinchou-google — APPROVED** [review]

**Comment by mhkawano** [comment]
Thanks for the review. It does not log closes, which I have updated it to do. We don't provide a way to reopen the prompt, so I don't think that's a concern.

**Pull request merged**
