### PR TITLE
Add es_419 translations

### PR DESCRIPTION
**Pull request by ed-bird**
Also update xlb files following on from  https://github.com/subscriptions-project/swg-js/commit/687fc84bafda05e07b64a0cd49c21c398159e879

### CODE REVIEW

**Review by elijahsoria — COMMENTED** [review]
I think if you revert your changes on src/i18n/strings.js it should fix the issue. I don't see any changes to the strings in the .xlb files, just strings.js and strings.js already has the updated message names.

**Comment by ed-bird** [comment]
> I think if you revert your changes on src/i18n/strings.js it should fix the issue. I don't see any changes to the strings in the .xlb files, just strings.js and strings.js already has the updated message names.

Yeah, I just wasn't sure because that was generated by running `yarn build-i18n` so I didn't know the implications of manually editing that file. Do you think it's safe to do that?

**Comment by elijahsoria** [comment]
> > I think if you revert your changes on src/i18n/strings.js it should fix the issue. I don't see any changes to the strings in the .xlb files, just strings.js and strings.js already has the updated message names.
> 
> Yeah, I just wasn't sure because that was generated by running `yarn build-i18n` so I didn't know the implications of manually editing that file. Do you think it's safe to do that?

I think it would be as long as they were working before the message name change, but I'm not 100% sure. @stellachui or @chenshay might be able to help here.

**Review by elijahsoria — APPROVED** [review]

**Comment by elijahsoria** [comment]
Approved with reverting strings.js

**Comment by stellachui** [comment]
> > > I think if you revert your changes on src/i18n/strings.js it should fix the issue. I don't see any changes to the strings in the .xlb files, just strings.js and strings.js already has the updated message names.
> > 
> > 
> > Yeah, I just wasn't sure because that was generated by running `yarn build-i18n` so I didn't know the implications of manually editing that file. Do you think it's safe to do that?
> 
> I think it would be as long as they were working before the message name change, but I'm not 100% sure. @stellachui or @chenshay might be able to help here.

I'm not sure why it's generating the UTF-8 encoding now, but it seems like using the HTML entities would be more flexible in case publisher sites are using non-UTF-8 encodings? I too would wait for @ChrisAntaki's take on this since he's much more familiar with this code than I am (I'm also interested in the answer). Sorry I can't be of more help.

**Comment by ChrisAntaki** [comment]
Hey! Could this wait until Tuesday?

**Comment by ChrisAntaki** [comment]
https://github.com/subscriptions-project/swg-js/pull/1493 adds a link to the guide. This PR also makes manual testing of Showcase Regwall languages easier by adding a new URL param (`html_lang`). Ex: "&html_lang=de"

**Comment by ed-bird** [comment]
Of course, no worries @ChrisAntaki !

Will wait for your push and redo this one.

**Comment by ChrisAntaki** [comment]
Sounds good, thanks!

**Comment by ed-bird** [comment]
Closing in favour of https://github.com/subscriptions-project/swg-js/pull/1497

**Pull request closed without merging**
