### PR TITLE
Docs link flow

### PR DESCRIPTION
**Pull request by plr108**
@jpettitt @dvoytenko please review.

Update OAuth account linking flow URLs.
Update link save flow documentation.
Update examples to show how to detect link save flow completion or user declining.
Change "reader" references to "user"

### CODE REVIEW

**Comment by jpettitt** [comment]
@plr108 please resolve merge conflict

**Comment by plr108** [comment]
Merge conflict resolved.  I incorporated the syntax highlighting from the commit from @ChrisAntaki.  I kept the javascript example from my earlier commit.

**Comment by plr108** [comment]
I consent

**Comment by ChrisAntaki** [comment]
I consent too 🙌

**Comment by ChrisAntaki** [comment]
I think it's complaining because your first two commits weren't associated with an email that was registered as having signed the CLA

**Comment by ChrisAntaki** [comment]
This might be helpful
https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by jpettitt** [comment]
Admin override merge since I know Patrick has signed the CLA

**Pull request merged**
