### PR TITLE
Add new events for error handling.

### PR DESCRIPTION
**Pull request by oyj9109**

### CODE REVIEW

**Comment by ChrisAntaki** [comment]
I'm seeing a lot of formatting changes. Just checking, did you save the scripts in a way that applied some automatic formatting from your IDE?

**Comment by ChrisAntaki** [comment]
With these automatically generated proto API messages and tests, it's best to avoid automatic formatting. That way, the code diffs can better highlight just what changed, between automatic generations

**Comment by oyj9109** [comment]
> With these automatically generated proto API messages and tests, it's best to avoid automatic formatting from our code editors. That way, the code diffs can better highlight just what changed between automatic generations

Those diffs were already in cl/485641504. I guess the piper linter got updated that it changed formatting there?

**Comment by ChrisAntaki** [comment]
The formatting seems inconsistent across the file for some reason

**Comment by ChrisAntaki** [comment]
Could you regenerate the files, so these diffs just highlight the additions?

**Comment by ChrisAntaki** [comment]
Hey Yeongjin! When you get a chance, could you check out this newly updated documentation for generating these API message JS files?

https://g3doc.corp.google.com/subscribewithgoogle/api/messages/README.md#instructions

Step 5 now describes copying the files without applying auto-formatting

**Comment by oyj9109** [comment]
Thanks for the reference, Chris. Closing this out as it's out dated.

**Pull request closed without merging**
