### PR TITLE
sendBeacon now uses request body

### PR DESCRIPTION
**Pull request by mborof**
Modifies the new sendBeacon interface so it sends logging data via the request body / form submission rather than putting everything into the URL string.

### CODE REVIEW

**Comment by mborof** [comment]
Just noting that I very specifically needed to figure out that Blob required a content type of "'application/x-www-form-urlencoded;charset=UTF-8';" before Chrome stopped erroring out when I tried to use blob.

**Comment by ChrisAntaki** [comment]
Nice! Which browsers have you tested at this point?

**Comment by ChrisAntaki** [comment]
Could you verify this works in iOS 12, iOS 13, Chrome, and Firefox?

**Comment by mborof** [comment]
I did just verify it works in "Firefox ESR" which is what we can install on our glinux machines...

**Pull request merged**
