### PR TITLE
Use important rule for Showcase CSS

### PR DESCRIPTION
**Pull request by ChrisAntaki**
Fixes http://b/202482741

### CODE REVIEW

**Review by mmmicedcoffee — COMMENTED** [review]
I read the description of the bug, and I'm a little confused about the root cause because I thought iframes don't inherit the styles from their parent/host page. Why are we seeing CSS interference for the contents of our iframe?

**Comment by ChrisAntaki** [comment]
Nice catch! I accidentally applied the `!important` rule to the iframe styles, instead of the Regwall styles. It should be fixed now

**Review by mmmicedcoffee — APPROVED** [review]
The fix makes more sense to me now!

What are your thoughts on rendering the regwall dialog in an iframe vs directly in swgjs like it is done now? The former pattern is more common with other SwG components, and it would avoid the styling issues that we're running into now.

**Comment by ChrisAntaki** [comment]
Good idea, I'll make a bug for the FriendlyIframe upgrade

**Pull request merged**
